import type { FieldDef } from '../field-types';

/** Panneaux solaires — photovoltaïque, thermique, autoconsommation. */
export const panneauxSolairesFields = [
  {
    key: 'typeInstallation',
    kind: 'enum',
    label: 'Type d’installation',
    required: true,
    showInPreview: true,
    options: [
      { value: 'photovoltaique', label: 'Photovoltaïque' },
      { value: 'thermique', label: 'Solaire thermique' },
      { value: 'hybride', label: 'Hybride' },
      { value: 'indecis', label: 'À déterminer' },
    ],
  },
  {
    key: 'objectif',
    kind: 'enum',
    label: 'Objectif principal',
    required: true,
    showInPreview: true,
    options: [
      { value: 'autoconsommation', label: 'Autoconsommation' },
      { value: 'revente', label: 'Revente totale' },
      { value: 'mixte', label: 'Autoconsommation + revente' },
      { value: 'eau_chaude', label: 'Eau chaude sanitaire' },
    ],
  },
  {
    key: 'surfaceToitureM2',
    kind: 'surface',
    label: 'Surface de toiture disponible',
    required: true,
    showInPreview: true,
    quality: { weight: 10, score: { kind: 'range', at: 20, to: 120 } },
    min: 5,
    max: 1000,
  },
  {
    key: 'orientationToiture',
    kind: 'enum',
    label: 'Orientation de la toiture',
    required: false,
    showInPreview: true,
    quality: { weight: 15, score: { kind: 'map', values: { sud: 1, sud_est: 0.85, sud_ouest: 0.85, est: 0.5, ouest: 0.5, nord: 0.1, inconnue: 0.4 } }, whenMissing: 0.4 },
    options: [
      { value: 'sud', label: 'Sud' },
      { value: 'sud_est', label: 'Sud-Est' },
      { value: 'sud_ouest', label: 'Sud-Ouest' },
      { value: 'est', label: 'Est' },
      { value: 'ouest', label: 'Ouest' },
      { value: 'nord', label: 'Nord' },
      { value: 'inconnue', label: 'Inconnue' },
    ],
    help: "Une orientation sud change radicalement le rendement estimé.",
  },
  {
    key: 'factureElectriqueMensuelle',
    kind: 'number',
    label: 'Facture électrique mensuelle',
    required: false,
    showInPreview: true,
    quality: { weight: 20, score: { kind: 'range', at: 60, to: 300 }, whenMissing: 0.15 },
    min: 10,
    max: 2000,
    unit: '€',
  },
  {
    key: 'proprietaire',
    kind: 'boolean',
    label: 'Propriétaire du logement',
    required: true,
    showInPreview: true,
    quality: { weight: 30, score: { kind: 'bool', whenTrue: 1, whenFalse: 0 } },
  },
  {
    key: 'delaiProjet',
    kind: 'enum',
    label: 'Délai du projet',
    required: true,
    showInPreview: true,
    quality: { weight: 25, score: { kind: 'map', values: { immediat: 1, moins_3_mois: 0.7, moins_6_mois: 0.35, reflexion: 0.05 } } },
    options: [
      { value: 'immediat', label: 'Immédiat' },
      { value: 'moins_3_mois', label: 'Moins de 3 mois' },
      { value: 'moins_6_mois', label: 'Moins de 6 mois' },
      { value: 'reflexion', label: 'En réflexion' },
    ],
  },
] as const satisfies readonly FieldDef[];
