import type { FieldDef } from '../field-types';

/** Toiture — réfection, nettoyage, isolation, urgences fuite. */
export const toitureFields = [
  {
    key: 'typeIntervention',
    kind: 'enum',
    label: 'Type d’intervention',
    required: true,
    showInPreview: true,
    quality: { weight: 20, score: { kind: 'map', values: { refection_totale: 1, isolation: 0.9, fuite: 0.8, reparation: 0.5, nettoyage: 0.3 } } },
    options: [
      { value: 'refection_totale', label: 'Réfection totale' },
      { value: 'reparation', label: 'Réparation ponctuelle' },
      { value: 'nettoyage', label: 'Nettoyage / démoussage' },
      { value: 'isolation', label: 'Isolation de toiture' },
      { value: 'fuite', label: 'Fuite / urgence' },
    ],
  },
  {
    key: 'typeCouverture',
    kind: 'enum',
    label: 'Type de couverture',
    required: true,
    showInPreview: true,
    options: [
      { value: 'tuiles', label: 'Tuiles' },
      { value: 'ardoise', label: 'Ardoise' },
      { value: 'zinc', label: 'Zinc' },
      { value: 'bac_acier', label: 'Bac acier' },
      { value: 'toit_plat', label: 'Toit plat / étanchéité' },
      { value: 'autre', label: 'Autre' },
    ],
  },
  {
    key: 'surfaceM2',
    kind: 'surface',
    label: 'Surface de toiture',
    required: true,
    showInPreview: true,
    quality: { weight: 10, score: { kind: 'range', at: 40, to: 250 } },
    min: 10,
    max: 2000,
  },
  {
    key: 'nombreEtages',
    kind: 'number',
    label: 'Nombre d’étages',
    required: false,
    showInPreview: true,
    min: 0,
    max: 10,
    help: "Détermine le besoin d'échafaudage, donc le montant du devis.",
  },
  {
    key: 'urgence',
    kind: 'boolean',
    label: 'Intervention urgente',
    required: true,
    showInPreview: true,
    quality: { weight: 20, score: { kind: 'bool', whenTrue: 1, whenFalse: 0.4 } },
  },
  {
    key: 'proprietaire',
    kind: 'boolean',
    label: 'Propriétaire du logement',
    required: true,
    showInPreview: true,
    quality: { weight: 30, score: { kind: 'bool', whenTrue: 1, whenFalse: 0 } },
  },
  {
    key: 'delaiProjet',
    kind: 'enum',
    label: 'Délai du projet',
    required: true,
    showInPreview: true,
    quality: { weight: 20, score: { kind: 'map', values: { immediat: 1, moins_3_mois: 0.7, moins_6_mois: 0.35, reflexion: 0.05 } } },
    options: [
      { value: 'immediat', label: 'Immédiat' },
      { value: 'moins_3_mois', label: 'Moins de 3 mois' },
      { value: 'moins_6_mois', label: 'Moins de 6 mois' },
      { value: 'reflexion', label: 'En réflexion' },
    ],
  },
] as const satisfies readonly FieldDef[];
